### ISSUE TITLE
Migrate to GitHub Actions for CI

### ISSUE THREAD

**Issue by dpogue** [AyogoHealth/ay-slide-wheel#9]

**Comment by saadismail** [comment]
I am working on it. Done with the implementation, just testing it and making sure that there is no issues.

Expect a PR with in 24 hours.

**Comment by dpogue** [comment]
For Hacktoberfest credit, you'll want to wait until after October 1st to open a PR

**Comment by saadismail** [comment]
Thank you for pointing it out. I am done with the CI pipeline and will send a PR in the start of October.
